### ISSUE TITLE
Admin Orders Dashboard

### ISSUE THREAD

**Issue by brettgrigsby** [adfink/dinner_dash#35]

**Comment by brettgrigsby** [comment]
As an authorized admin
when i visit '/orders'
I See a listing of all orders with:
the total number of orders by status
links for each individual order
filter orders to display by status type (for statuses "ordered", "paid", "cancelled", "completed")

link to transition to a different status:
link to "cancel" individual orders which are currently "ordered" or "paid"
link to "mark as paid" orders which are "ordered"
link to "mark as completed" individual orders which are currently "paid"

**Comment by chelseaworrel** [comment]
need to write tests
