### ISSUE TITLE
Admin Order Show

### ISSUE THREAD

**Issue by brettgrigsby** [adfink/dinner_dash#36]

**Comment by brettgrigsby** [comment]
as an auth admin
when i visit an order's show page
i see details of an individual order, including:
Order date and time
Purchaser full name and email address
For each item on the order:
Name linked to the item page
Quantity
Price
Line item subtotal
Total for the order
Status of the order

**Comment by chelseaworrel** [comment]
this is finished but I did it without any tests....so write tests :)
